### ISSUE TITLE
Maintain Available Languages

### ISSUE THREAD

**Issue by Gonzalo2310** [ElemeFE/vscode-element-helper#10]
With the existing Spanish documentation. Can you add this parameter to the extension for VsCode?
![captura de pantalla 2017-12-29 a las 5 12 33](https://user-images.githubusercontent.com/6000947/34429327-1ca25fe6-ec57-11e7-8b6a-3cbc62b76300.png)

**Comment by ShowJoy** [comment]
Support spanish now.
