### ISSUE TITLE
command 'element-helper.searchUnderCursor' not found

### ISSUE THREAD

**Issue by bengban** [ElemeFE/vscode-element-helper#13]
vs-code-version:  1.23.0-insider (1.23.0-insider)

error: command 'element-helper.searchUnderCursor' not found

**Comment by ShowJoy** [comment]
I downloaded this version, but did not find this error.  can you provide more detail? 
btw, are you install plugin 'vetur' ? if not, please install.

**Comment by Darkbish** [comment]
I had this problem after update to version 1.22.1, I solved it by followed steps:

1. uninstall the extension
2. delete the folder `%USER_PROFILE%/.vscode/extensions/ElemeFE.vscode-element-helper-0.5.2` 
3. reinstall the extension.
