### ISSUE TITLE
Code generate default upper camel case bug

### ISSUE THREAD

**Issue by DiscoverForever** [ElemeFE/vscode-element-helper#23]
<img width="489" alt="屏幕快照 2019-03-29 下午2 44 45" src="https://user-images.githubusercontent.com/16662687/55214371-88974180-5231-11e9-8e28-9be99755b409.png">
default code style is upper camel case <br>
I want use kebab case <br>
Could you let users choose their own code style?
<img width="462" alt="屏幕快照 2019-03-29 下午2 53 42" src="https://user-images.githubusercontent.com/16662687/55214734-7bc71d80-5232-11e9-8aa5-1f677ee761c6.png">

**Comment by GreatFireWall** [comment]
Same problem to me.
