### ISSUE TITLE
无法查看在线文档

### ISSUE THREAD

**Issue by Lurkerc** [ElemeFE/vscode-element-helper#5]
vscode:
![image](https://user-images.githubusercontent.com/11989045/28504980-ba64fa68-7051-11e7-9119-5dab6ba30bc0.png)
在线文档查看：
![image](https://user-images.githubusercontent.com/11989045/28505022-04f9fb78-7052-11e7-8fc0-c2c111d72289.png)

刚启动vscode的时候就提示检查网络，但是电脑一直处于联网状态

**Comment by ShowJoy** [comment]
你重新加载了没有？

**Comment by Lurkerc** [comment]
![image](https://user-images.githubusercontent.com/11989045/28518233-c12127c6-7099-11e7-907b-99f02252b801.png)
卸载后重新安装也是这样，打开在线文档一直是加载动画。

**Comment by ShowJoy** [comment]
可能是windows系统，没测试过。我找台机器试下~~~

**Comment by EdenSpark** [comment]
我也遇到了同样的问题，一直处于加载状态
![image](https://user-images.githubusercontent.com/9413415/28609293-badf0382-7216-11e7-8f7b-c1c96b666742.png)
![image](https://user-images.githubusercontent.com/9413415/28609326-d2acdde0-7216-11e7-9519-c4b35bf775cf.png)

**Comment by ShowJoy** [comment]
@Lurkerc @EdenSpark 已修复，请先更新版本。设置git.path为你安装的git.exe的路径地址，比如："C:\\Program Files\\Git\bin\\git.exe"。最后不行的话请更新git 版本到2以上,再到配置文件中设置git.path

**Comment by Lurkerc** [comment]
好的，非常感谢

**Comment by ThinkRealize** [comment]
@ShowJoy  无法查看文档，和他们遇到一样的问题，设置 git.path 后还是无效。
系统：osx 10.12.6
vscode 版本：1.14.2
插件版本： 0.3.0
settings：
  "element-helper.version": "1.4",
  "git.path": "/usr/local/git/bin/git"
git verstion:
![git](https://user-images.githubusercontent.com/13347370/28951634-e5bf1ddc-78fe-11e7-884c-e1b447aee901.png)

**Comment by ShowJoy** [comment]
执行which git， 复制目录到git.path

**Comment by ThinkRealize** [comment]
@ShowJoy 我的是可以在 terminal 里直接输入 git，还是不能加载文档。
vscode 开发者工具报的警告。
[Extension Host] Error: An extension called process.exit() and this was prevented.
    at Object.process.exit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:427537)
    at shelljs_1.exec (/Users/ly/.vscode/extensions/ElemeFE.vscode-element-helper-0.3.0/out/src/library.js:98:35)
    at /Users/ly/.vscode/extensions/ElemeFE.vscode-element-helper-0.3.0/node_modules/shelljs/src/exec.js:204:9
    at ChildProcess.exithandler (child_process.js:230:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by ShowJoy** [comment]
@ThinkRealize 
1.安装后什么时候出现提示‘Load document failure, please check your network and reload.’，大约过了多久？是不是网络问题？
2.尝试cd ~/.vscode/extensions/ElemeFE.vscode-element-helper-0.3.0/resources 目录,依次执行：
mkdir element-gh-pages
cd element-gh-pages
git init 
git remote add -t gh-pages -f origin git@github.com:ElemeFE/element.git
git checkout gh-pages
看下是否能成功？

**Comment by ThinkRealize** [comment]
@ShowJoy 插件启动的时候就报错。网络问题可排除。按照你的建议操作，执行： 
git remote add -t gh-pages -f origin git@github.com:ElemeFE/element.git，时出错：
fatal: remote origin already exists.
使用 git GUI 工具链接远程提示如下错误：
Permission denied (publickey).
fatal: Could not read from remote repository.
使用 ssh 链接远程，会提示没有权限。。。
使用 https 链接远程是成功的。

**Comment by ShowJoy** [comment]
1.你先要删除element-gh-pages目录，先前已经执行了命令所以报错：fatal: remote origin already exists.
2.使用ssh是需要配ssh-key的。。。，这很尴尬
3.官网说[https](https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-urls-recommended)方式是需要输入用户名和密码的，但我本地运行不需要这些，我很纳闷。难道是公共库git clone, fetch是不需要？
我考虑做下兼容处理，感谢 @ThinkRealize

**Comment by ThinkRealize** [comment]
@ShowJoy ssh 配置 ssh-key 后会被记录，以后链接时就会默认使用已有的。https 也是同样，第一次时需要输入用户名和密码，以后链接会使用已有的用户名和密码。在 osx 上用户名和密码可以在钥匙串访问应用中查看，linux 和 windows 也有同样的机制。希望以上信息对你有帮助。

**Comment by ThinkRealize** [comment]
该扩展现在是使用 ssh 链接 github，在兼容处理更新前如果遇到 Load document failure, please check your network and reload，请尝试配置 ssh-key，并添加到 github 中。

**Comment by ShowJoy** [comment]
@ThinkRealize done! 非常感谢。
